server:
  port: 8080

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yml
  datasource:
    url: jdbc:postgresql://localhost:5435/DynamikaDB
    username: PavelMikh
    password: 123dynamika321
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
springdoc:
  swagger-ui:
    path: /dynamika
  api-docs:
    path: /swagger-dynamika-api-docs